# feature-service-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-service-deployment
  template:
    metadata:
      labels:
        app: feature-service-deployment
    spec:
      containers:
      - name: feature-service
        image: gcr.io/nycdsa-project-4/feature-service:latest
        env:
        - name: DB_FEATURE_SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: db_feature_service_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: db_port
        - name: POLYGON_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: polygon_api_key