# feature-service-init-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-service-initialize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-service-initialize
  template:
    metadata:
      labels:
        app: feature-service-initialize
    spec:
      containers:
      - name: feature-service
        image: gcr.io/nycdsa-project-4/feature-service-initialize:latest
        env:
        - name: DB_HOST
          value: 172.30.192.3
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password