# frontend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: frontend-dashboard-service
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: ???